import { CalendarDays, Heart, MapPin, Shield, Star, UsersRound, Wallet, X } from 'lucide-react';
import { useEffect } from 'react';

export function ReportDetailsModal({ report, onClose }) {
  useEffect(() => {
    const closeOnEscape = (event) => { if (event.key === 'Escape') onClose(); };
    window.addEventListener('keydown', closeOnEscape);
    return () => window.removeEventListener('keydown', closeOnEscape);
  }, [onClose]);
  if (!report) return null;
  const photos = report.photos?.length ? report.photos : report.image ? [{ url: report.image, name: report.destination }] : [];
  return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4 backdrop-blur-sm" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><article className="max-h-[90vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white shadow-2xl" role="dialog" aria-modal="true" aria-labelledby="report-details-title"><header className="sticky top-0 z-10 flex items-center justify-between border-b border-slate-100 bg-white/95 px-5 py-4 backdrop-blur"><div className="flex items-center gap-3"><img src={report.avatar} alt="" className="h-11 w-11 rounded-full object-cover" /><div><h2 id="report-details-title" className="font-extrabold text-slate-950">Relato de {report.author}</h2><p className="text-xs text-slate-500">{report.destination}</p></div></div><button type="button" onClick={onClose} className="grid h-9 w-9 place-items-center rounded-full text-slate-500 hover:bg-slate-100" aria-label="Fechar detalhes"><X size={19} /></button></header><div className="space-y-5 p-5"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><Detail icon={MapPin} label="Destino" value={report.destination} /><Detail icon={CalendarDays} label="Quando" value={report.date || 'Não informado'} /><Detail icon={UsersRound} label="Tipo" value={report.travelType || 'Não informado'} /><Detail icon={Wallet} label="Gastos" value={report.cost || 'Não informado'} /></div><section><h3 className="text-sm font-extrabold text-slate-950">Experiência completa</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-700">{report.text}</p></section>{photos.length > 0 && <section><h3 className="text-sm font-extrabold text-slate-950">Fotos da viagem</h3><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{photos.map((photo, index) => <img key={`${photo.url}-${index}`} src={photo.url} alt={photo.name || `${report.destination} ${index + 1}`} className="h-40 w-full rounded-2xl object-cover" />)}</div></section>}<div className="flex flex-wrap gap-2 border-t border-slate-100 pt-4"><span className="inline-flex items-center gap-1.5 rounded-full bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><Shield size={14} /> Segurança: {report.safety || 'Não informada'}</span>{report.rating ? <span className="inline-flex items-center gap-1.5 rounded-full bg-amber-50 px-3 py-2 text-xs font-bold text-amber-700"><Star size={14} fill="currentColor" /> Avaliação: {report.rating}/5</span> : null}<span className="inline-flex items-center gap-1.5 rounded-full bg-rose-50 px-3 py-2 text-xs font-bold text-rose-700"><Heart size={14} /> {report.likes || 0} curtidas</span><span className="rounded-full bg-slate-100 px-3 py-2 text-xs font-bold text-slate-600">Duração: {report.duration || 'Não informada'}</span></div></div></article></div>;
}

function Detail({ icon: Icon, label, value }) {
  return <div className="rounded-xl bg-slate-50 p-3"><Icon size={15} className="text-brand-600" /><p className="mt-2 text-[10px] uppercase tracking-wide text-slate-400">{label}</p><p className="mt-0.5 text-xs font-bold text-slate-800">{value}</p></div>;
}
